openapi: "3.0.2"
info:
  title: Order Tracker API
  version: "1.0"
servers:
  - url: https://
paths:
  /test:
    get:
      responses:
        "200":
          description: OK

  /customers:
    get:
      description: "Returns a list of all the customers."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of customers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "400":
          description: Invalid request.

  /customers/customer_id:
    get:
      description: 'Obtain information about an artist from their unique customer_id'
      parameters:
        - name: customer_id
          in: path 
          required: true
          schema:
            type: string
            items:
              $ref: "#/components/schemas/Customer"
              
      responses:
        '200':
          description: Successfully returned a customer


components:
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: integer
        first_name:
          type: string
        middle_initial:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
        customer_notes:
          type: string
        billing_address_id:
          type: integer
        is_active:
          type: boolean



