openapi: "3.0.2"
info:
  title: Order Tracker API
  version: "1.0"
servers:
  - url: https://
paths:
  /customers:
    get:
      description: "Returns a list of all the customers."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of customers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "400":
          $ref: "#/components/responses/400Error"

    post:
      description: "Let a user create a new customer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "201":
          description: Successfully added a new customer
        "400":
          $ref: "#/components/responses/400Error"

  /customers/{customer_id}:
    get:
      description: "Obtain information about a customer from their unique customer_id"
      parameters:
        - name: customer_id
          in: path
          required: true
          schema:
            type: string

      responses:
        "201":
          description: Successfully returned the customer referenced by customer_id.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "400":
          $ref: "#/components/responses/400Error"

  /addresses:
    get:
      description: "Get all of the system's addresses."
      parameters: []
      responses:
        "200":
          description: Successfully returned addresses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"

    post:
      description: "Create a new address."
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      responses:
        "201":
          description: Successfully added address.
        "500":
          description: Address endpoint error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /addresses/{addressId}:
    get:
      description: "Get an address by address_id."
      parameters:
        - name: addressId
          description: The id of the address to be returned.
          in: path
          required: true
          schema:
            type: string

      responses:
        "201":
          description: Successfully returned the address referenced by addressId.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"

        "500":
          description: Address endpoint error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /orders:
    get:
      description: "Returns a list of all orders."
      parameters: []
      responses:
        "200":
          description: Successfully returned orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "400":
          $ref: "#/components/responses/400Error"
    post:
      description: 'Create a new order'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        '201':
          description: Successfully added new order 
        '400':
          $ref: "#/components/responses/400Error"


  /orders/{order_id}:
    get:
      description: "Obtain order from unique order_id"
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully returned the Order referenced by Order_ID.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "404":
          description: Order ID not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /Details:
    get:
      description: "Returns a list of all orders detail rows."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of orders details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Detail"
        "400":
          $ref: "#/components/responses/400Error"
    post:
      description: 'Create new order detail'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Detail"
      responses:
        '201':
          description: Successfully added a new order detail
        '400':
          $ref: "#/components/responses/400Error"
  /Details/{order_details_id}:
    get:
      description: "Obtain order detail from their unique order_details_id"
      parameters:
        - name: order_details_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully returned the order detail referenced by order_details_id.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Detail"
        
        "404":
          description: Failed GET request for order detail with ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string




components:
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: integer
        first_name:
          type: string
        middle_initial:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
        customer_notes:
          type: string
        billing_address_id:
          type: integer
        is_active:
          type: boolean

    Address:
      type: object
      properties:
        address_id:
          type: integer
        street:
          type: string
        apt_num:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string

    Order:
      type: object
      properties:
        order_id:
          type: integer
        customer_id:
          type: integer
        order_status_code:
          type: integer
        order_placed:
          type: string
        order_notes:
          type: string
        shipping_address_id:
          type: integer

    Detail:
      type: object
      properties:
        order_details_id:
          type: integer
        order_id:
          type: integer
        product_id:
          type: integer
        product_quantity:
          type: integer

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
