openapi: "3.0.2"
info:
  title: Order Tracker API
  version: "1.0"
servers:
  - url: https://
paths:
  /customers:
    get:
      description: "Returns a list of all active customers."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of active customers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "500":
          description: API server connection refused

    post:
      description: "Let a user create a new customer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "201":
          description: Successfully added a new customer
        "500":
          description: Sequelize couldn't validate body, likely missing required object fields

  /customers/{customer_id}:
    get:
      description: "Obtain information about a customer from their unique customer_id"
      parameters:
        - name: customer_id
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Successfully returned the customer referenced by customer_id.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "404":
          description: Customer with passed customer_id not found
        
    patch:
      description: "Edit the existing customer referenced by customer_id"
      parameters:
        - name: customer_id
          description: The customer id of the customer to be edited/patched.
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Successfully edited the customer referenced by customer_id.
        "404":
          description: Request successful but no customer found with matching customer_id

    put:
      description: "Modify existing customer referenced by customer_id."
      parameters:
        - name: customer_id
          description: The code of the customer to be modified.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Successfully modified the customer referenced by customer_id.
        "404":
          description: Request successful but no customer found with matching customer_id

    delete:
      description: "Delete a customer by customer_id"
      requestBody:
        required: true
        content:
          application/json:
           schema:
            $ref: "#/components/schemas/Customer"
      responses:
        "204":
          description: Successfully deleted the customer referenced by customer_id.
        "404":
          description: Request successful but no customer found with matching customer_id

  /customers/all:
    get:
      description: "Returns a list of all customers (active and non-active)."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of all customers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "500":
          description: API Server connection refused
  
  /customers/search?email=[email]:
    get:
      description: "Search for customer by email."
      parameters: 
        - name: email
          description: The email of the customer to be found
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully found customer with passed email parameter.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

        "404":
          description: Request successful but no customer found by the passed email parameter


components:
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: integer
        first_name:
          type: string
        middle_initial:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
        customer_notes:
          type: string
        billing_address_id:
          type: integer
        is_active:
          type: boolean
    
    Address:
      type: object
      properties:
        address_id:
          type: integer
        street:
          type: string
        apt_num:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string

  
