openapi: "3.0.2"
info:
  title: Order Tracker API
  version: "1.0"
servers:
  - url: https://
paths:
  /Details:
    get:
      description: "Returns a list of all orders detail rows."
      parameters: []
      responses:
        "200":
          description: Successfully returned a list of orders details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Detail"
        "400":
          $ref: "#/components/responses/400Error"
    post:
      description: "Create new order detail"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Detail"
      responses:
        "201":
          description: Successfully added a new order detail
        "400":
          $ref: "#/components/responses/400Error"

  /Details/{order_details_id}:
    get:
      description: "Obtain order detail from their unique order_details_id"
      parameters:
        - name: order_details_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully returned the order detail referenced by order_details_id.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Detail"

        "404":
          description: Failed GET request for order detail with ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    patch:
      description: "Edit an existing order detail referenced by customer_id."
      parameters:
        - name: order_details_id
          description: The order details id of the order detail to be edited/patched.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Detail"
      responses:
        "200":
          description: Successfully edited the order detail referenced by order_details_id.
        "404":
          description: Request successful but no order detail found with matching order_details_id

    put:
      description: "Modify existing order detail referenced by order_details_id."
      parameters:
        - name: order_details_id
          description: The order detail to be modified.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Detail"
      responses:
        "200":
          description: Successfully modified the order detail referenced by order_details_id.
        "404":
          description: Request successful but no order detail found with matching order_details_id

    delete:
      description: "Delete an existing order detail by order_details_id"
      requestBody:
        required: true
        content:
          application/json:
           schema:
            $ref: "#/components/schemas/Detail"
      responses:
        "204":
          description: Successfully deleted the order detail referenced by oder_details_id.
        "404":
          description: Request successful but no order detail found with matching order_details_id

components:
  schemas:
    Detail:
      type: object
      properties:
        order_details_id:
          type: integer
        order_id:
          type: integer
        product_id:
          type: integer
        product_quantity:
          type: integer

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
