name: CI pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DB_USER: dbadmin
  DB_HOST: capstone-order-tracker-db.mysql.database.azure.com
  DB_PORT: 3306
  DB_SCHEMA: capstone_ots
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  main-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build --if-present

      - run: npx eslint . --ext .js,.jsx,.ts,.tsx --ignore-pattern "server/public/js"

      - run: npm run coverage:mocha

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectKey=EICPCohort7_capstone-order-tracker
            -Dsonar.organization=eicpcohort7-1
